public class RobotArm15{
    public static void main (String[] args){
System.out.println("setelah Langkah 1 : Nampan A :kosong, Nampan B : bulan, Nampan C : Bintang") ;
System.out.println("setelah Langkah 1 : Nampan A :Bulan, Nampan B : kosong, Nampan C : Bintang") ;
System.out.println("setelah Langkah 1 : Nampan A :Bulan, Nampan B : bintang, Nampan C : Kosong") ;
System.out.println("Pernyataan yang benar Adalah : (a) Kedua bola sudah bertukar tempat,(e) nampan C kosong");
}   
}